services:
  auth_service:
    container_name: auth_service
    build:
      context: auth_service/
      dockerfile: Dockerfile
    ports:
      - $AUTH_SERVICE_PORT:$AUTH_SERVICE_PORT
    env_file:
      - .env
    links:
      - db

  post_service:
    container_name: post_service
    build:
      context: post_service/
      dockerfile: Dockerfile
    ports:
      - $POST_SERVICE_PORT:$POST_SERVICE_PORT
    env_file:
      - .env
    links:
      - db

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ./postgres/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    env_file:
      - .env
